# Stage 1: Build Python app
FROM public.ecr.aws/lambda/python:3.8 AS builder

WORKDIR /app

ARG FUNCTION_FILE
COPY ${FUNCTION_FILE} .
COPY requirements.txt .

# 🔧 Install zip
RUN yum install -y zip

# Install Python dependencies if requirements.txt is not empty
RUN if [ -s requirements.txt ]; then \
  pip install -r requirements.txt -t .; \
  fi

ARG ZIP_NAME
RUN zip -r ${ZIP_NAME} .

# Stage 2: Minimal image to extract zip
FROM alpine:3.17

WORKDIR /app
COPY --from=builder /app/${ZIP_NAME} .

CMD ["sleep", "infinity"]
