
FROM public.ecr.aws/lambda/python:3.8 AS builder

WORKDIR /app

ARG FUNCTION_FILE=create_link.py
COPY ${FUNCTION_FILE} .
# COPY requirements.txt .  

# # Install dependencies if any (skip if empty)
# RUN if [ -s requirements.txt ]; then \
#       pip install -r requirements.txt -t .; \
#     fi

# Stage 2: Create the zip file
FROM alpine:3.17

RUN apk add --no-cache zip
WORKDIR /app

COPY --from=builder /app /app

ARG ZIP_NAME=create_link.zip
RUN zip -r /${ZIP_NAME} .
